version: "2"
services:
  builder:
    image: openlmis/dev-ui:1
    working_dir: /app
    volumes:
      - '.:/app'
    command:
      - './build.sh'
    env_file: .env
  image:
    build: .
    image: openlmis/requisition-refui